### PR TITLE
Add transfo spatial deformation from niftinet

### PR DESCRIPTION
**Pull request by romainVala**
it is working but very slow
it will be nice to have it running on the gpu, but no idea if it may be possible with sitk dependance

### CODE REVIEW

**Comment by romainVala** [comment]
I just make the changes to make it dependant on Transform class
Is there something missing ?

**Comment by fepegar** [comment]
Hi @romainVala, can you please adapt it to the new design and give it a try? Otherwise, I'll do it next week.

**Comment by fepegar** [comment]
I just tried and had a weird result: only about a section of the image is modified. But I'll keep working on this. Thanks again, @romainVala!

**Comment by fepegar** [comment]
Related to #4

**Comment by fepegar** [comment]
@all-contributors please add @romainVala for code

**Pull request merged**
