### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by GFabien**
- Add tests (mainly about transforms)
- Refactor `RandomTransform.parse_range` to `Transform` and expand it to deal with ranges with specific constraints.
- Reinforce transform arguments' parsing
- Correct a problem with `Image` path handling (cropping an image without path was copying path `''` instead of `None`)
- Correct a problem with `RandomNoise` that made some tests failed in `test_transforms.py`
- Propose a minor change to `RandomSpike` (aims to be more intuitive: an `intensity` of `0` used to introduce an artifact while now an `intensity` of `0` does not produce any artifact)

### CODE REVIEW

**Comment by GFabien** [comment]
Ok, my local torch version was accepting to have `0.0` standard deviation value in `normal_` but it is not the case for the Travis build. Any reason to choose `normal_` rather than `randn(...) * std + mean`?

**Comment by fepegar** [comment]
Wow, this is impressive! You probably know the library better than me by now :D These are very helpful, and much needed changes.

One little thing. In `RandomDownsample`, the correct syntax for the Python example in the docstring for multiline statements is `...` instead of `>>>`.

> Ok, my local torch version was accepting to have 0.0 standard deviation value in normal_ but it is not the case for the Travis build. Any reason to choose normal_ rather than randn(...) * std + mean?

No reason. As long as the random parameters are computed by PyTorch (and not NumPy or Python) and results are the same, I guess it's fine for most cases.

**Comment by GFabien** [comment]
> One little thing. In RandomDownsample, the correct syntax for the Python example in the docstring for multiline statements is `...` instead of `>>>`.

Ok thanks!

> No reason. As long as the random parameters are computed by PyTorch (and not NumPy or Python) and results are the same, I guess it's fine for most cases.

I haven't found much information comparing both. I know that `randn(...) * std + mean` allows the variables to be differentiable w.r.t. the mean and variance but we don't care about that here. It seems that `normal_` does not allow to take a zero standard deviation so I would rather choose `randn(...) * std + mean` but it does not change much.

**Comment by fepegar** [comment]
Can you please switch to `randn` and fix the docstring? We can then merge, I think.

**Comment by GFabien** [comment]
Sure, I will also add some tests about cropping images because I found a bug when cropping `ScalarImage` and `LabelMap`: type is copied to the new instance but when a type is given to one of the child classes, an error is raised.

```python
import torch
from torchio import ScalarImage

data = torch.ones((10, 10, 10))
image = ScalarImage(tensor=data)
image.crop((1, 1, 1), (5, 5, 5))
```

**Comment by fepegar** [comment]
Damn! Good catch!

**Comment by fepegar** [comment]
Maybe we should just drop the `type` kwarg in `v0.18`. It was useful when we used to use `dict`s, but with proper classes and inheritance, there's no point, I think.

**Comment by GFabien** [comment]
I made a little change to fix it without removing `kwargs` but feel free to change it if you want!

**Comment by fepegar** [comment]
Added in `v.0.17.14`. Thanks again!

**Pull request merged**
