### PR TITLE
Support for HDF5 Datasets as Image

### PR DESCRIPTION
**Pull request by soumickmj**
Wrapper for the Image class, enabling it to be used with HDF5 dataset instead of files or arrays or tensors. Also adds functionality for lazy loading of patches.

### CODE REVIEW

**Comment by fepegar** [comment]
Hi, @soumickmj, looking good! Instead of asking you directly for specific modifications, I'm going to paste here the new PR template. Let me know if you have any questions!

Also, it would be great if you could share a file or a URL so that I can try this.

---


Fixes # .

**Description**
A few sentences describing the changes proposed in this pull request.

**Checklist**

You do not need to complete all the items by the time you submit the pull
request, but most likely the changes will only be merged if all the tasks are
done. See more information about the submission process in the
[`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/master/CONTRIBUTING.rst) docs.


- [ ] Development setup performed as explained in [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/master/CONTRIBUTING.rst)
- [ ] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [ ] Tests added or modified to cover the changes
- [ ] Integration tests passed locally by running `pytest`
- [ ] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [ ] This pull request is ready to be reviewed

**Comment by soumickmj** [comment]
@fepegar I have combined the wrapper directly into the image class and also added tests for the same. Additionally, I have also added docstrings. It looks like all checks have passed as well. Can you please tell me if I should do anything else? Thanks.

**Comment by fepegar** [comment]
Awesome! Please take a look at the last point in https://github.com/fepegar/torchio/pull/323#issuecomment-701686044, then I'll check the code.

**Comment by soumickmj** [comment]
@fepegar creating a fresh pull request. And I looked into the last comment and followed the checklist already.
Regarding the H5 file, do you still need it? In the tests, I have created a function to create H5 files for testing.

**Comment by fepegar** [comment]
> @fepegar creating a fresh pull request

Ok!

> And I looked into the last comment and followed the checklist already.

Thanks!

> Regarding the H5 file, do you still need it? In the tests, I have created a function to create H5 files for testing.

In that case, I suppose we don't need one. I'll just take a look at the test.

**Pull request closed without merging**
