### PR TITLE
Improve random transforms reproducibility

### LINKED ISSUE #191: Seeding in Transform, make the same transform all the time
**🐛Bug**
I notice it at least for RandomAffine RandomElastic and RandomNoise

**To reproduce**
```
t = Compose([RandomNoise(seed=10)])
dataset = ImagesDataset(suj, transform=t); 

sample=dataset[0]
for i in range(0, 10):
    sample = dataset[0]
    h=sample.history
    print(h[0][1]['image']['std'])

```

Now change seed=10 to seed=None and you get a diferent number each time

I thing it is due to this line
https://github.com/fepegar/torchio/blob/0e8172c3253050fcbf309989b57cdf9e81a3cc6c/torchio/transforms/augmentation/random_transform.py#L32

it should not be called here, juste once in the init()

### PR DESCRIPTION
**Pull request by fepegar**
Resolves #191, #208.

I will also add docs on reproducibility, and maybe a notebook.

### CODE REVIEW

**Comment by romainVala** [comment]
Hi
Nice PR, as most of the change is to remove code from the transform, since now save and get history is done in the subject class

I am still not sure, that to do not have the possibility to add 'normal parameter" in the history, (as it was before) is a good idea, 

Let consider random Elastic where you have to  specify the num_control_point, having only the seed saved in the history, will allow to reproduce the same transform, if and only if you put the name num_control_point
Why not saving it to the history

Other drawback of this changes, is for simple transform without random choise (like rescale or normalization), I would like to add the chosen parameter in the history too, 

but with those changes, you can now only log seed ... non ?

**Comment by fepegar** [comment]
The problem with this implementation is that intensity transforms use different parameters for the different images in the `Subject`. Either we use the same for all, or we use a more complex transforms history...

> Let consider random Elastic where you have to specify the num_control_point, having only the seed saved in the history, will allow to reproduce the same transform, if and only if you put the same num_control_point
Why not saving it to the history ?

Because the user has control over what parameters they passed to the transform.

**Comment by romainVala** [comment]
> Because the user has control over what parameters they passed to the transform.
yes but it makes the code more difficult (with hard coded parameter valuer), I really thing it will be more efficient to read it directly from the history (given the fact it is so simple to add !)

applying transform and reading parameters, should be dissociate

I can think at an example where you do not know : let say you want to compare the influence of num_control_point, and you define OneOf transform with 2 randomElastic call each of them with different num_control_point

**Comment by romainVala** [comment]
sorry to insist, but I really like to convince you on this point 

Once you performed multiple experiment, with different transform, it is convenient to just have a look to save history in order to know what has been applied
I loose this explicit reading if we now store only the seed, but at least I can make a function that will convert the stored seed in real parameters, but for the completeness I also need the "fixed parameters"

It is also a way to check that every thing was done as planed (which is important too)

The objective is to be able to recreate a given transformed volume (because the model is very bad for this volume) why should I need to remember which num_control_point I set (or which percentiles I set for  RescaleIntensity) if those parameters can be stored in the history I have an autonomous mechanism to reproduce the given transform without prior knowledge
so I can write a generic function to reproduce any given transform (from its saved history)

don't you think it is much better so ?

If there are some drawback to store all parameters, let's make it optional, but I think it is a great feature, to make this full parameter recording possible

**Comment by romainVala** [comment]
> The problem with this implementation is that intensity transforms use different parameters for the different images in the `Subject`. Either we use the same for all, or we use a more complex transforms history...

given what has been discuss here #238 we will need a more complex transforms history ... 
may be instead of having a list containing 
[ <transform_name> , transform_dict_param] 
we will have
[ <transform_name> , [<image_key>, transform_dict_param] ]
(and if the same transform is apply to all we will take the previous one)

**Pull request closed without merging**
