### PR TITLE
118 resample to target spacing

### PR DESCRIPTION
**Pull request by nwschurink**
In the resampling transform, I have added the possibility to resample all images to a common voxelgrid as discussed in issue #118  

It's the first time I have been working directly on a package, so if you have any comments on the code I'm glad to get some feedback ;)

### CODE REVIEW

**Comment by nwschurink** [comment]
Ah, I just see that I forgot to add one check.

When target_spacing=None and a reference_spacing is given, it will check the input and resample everything to the reference spacing. However, when both target_spacing and reference_spacing are None it will try to perform regular resampling with an undefined target_spacing.

Can I edit this using the github code review?

**Comment by fepegar** [comment]
Could you please squash into a single commit and force-push? That way I can see the changes more easily. Here's some help: https://github.com/Slicer/Slicer/pull/4789#issuecomment-606791186

**Comment by fepegar** [comment]
Looking good! I'm going to make some changes. We should have some tests, too.

**Comment by fepegar** [comment]
I refactored a bit and added some tests.

**Comment by nwschurink** [comment]
Code looks good 👍 

I think the warning message would be good. If the images are of different size, you'd run into a lot of issues either with other transforms or in your deep learning pipeline.

So maybe, if a target space is passed and images have a different size the warning could also include a hint that you should first resample to a common voxelgrid right? E.g. if you have overlapping images with different sizes and different voxelgrids you'd need 2 transforms e.g.:

```
transforms =[ torchio.transforms.Resample(target='t1'),
                    torchio.transforms.Resample(target=(1,1,1))]
transform = Compose(transforms)
```

**Comment by romainVala** [comment]
Sorry if I miss the point, but I do not understand, 
if input images have different size, after resample to target, they all will have the target shape, (this is one interest of this transform)
what do I miss ?

**Comment by romainVala** [comment]
ok, I see, the title, retarget='t1' mean you chose the pixel size from the t1 image ? is that correct ?

Why not to make  a "full" resampling ... ie: the resampled image will have the exact same affine as the reference image (this is what nibabel.resample_from_to() function does) ... ?

**Comment by nwschurink** [comment]
@romainVala you are right that if you resample to a target they will have the same target shape. But what if your target doesn't have your desired voxelsize? For my usecase I have images of different sizes that I all want to have in the same field of view (e.g. my `target='t2'`). My target image however has voxelsize `(0.7,0.7,2)` and I want this to be (1,1,1). So that means you'd need to chain the Resample transform.

I understood @fepegar was referring to the case where you have input images of different size, you resample to a certain spacing (e.g. (1,1,1) isotropic) but forget to resampling to a common target first. Then the endresult will be images with 1mm isotropic voxels but will still be of different size?

**Comment by nwschurink** [comment]
I'm not sure if I follow exactly what you're saying. The target='t1' already does a "full" resampling to the 't1' voxelgrid using `nibabel.resample_from_to()` right?

**Comment by romainVala** [comment]
ok thanks for the clarification, we do agree, 
I just though warning was intended, when one use target='t1', but as you said, this is for the case where one use resample to voxel size (1,1,1)
make sense

I can think of one example where the message does not apply
For instance if you do the resample to 1,1,1 and then use CropAndPad (to a specific size), in this case it solve the problem of having different size, (without having to first resample to a target space)

**Comment by fepegar** [comment]
> I can think of one example where the message does not apply
For instance if you do the resample to 1,1,1 and then use CropAndPad (to a specific size), in this case it solve the problem of having different size, (without having to first resample to a target space)

I agree. What about a warning in the docs instead?

**Comment by nwschurink** [comment]
I think the docs would also be good, it's probably the first place people will look :).

**Comment by nwschurink** [comment]
There is still one thing that I'm wondering about. CropAndPad won't accept images of different sizes and will only work when the voxelgrids are already align right?

Because, if you have images with different voxelgrids. If you would resample them to isotropic voxels without also resampling to a common target space and then use CropAndPad. The resampled images will indeed have the same voxelsize and have the same shape after CropAndPad. However a voxel at location (x,y,z) in one image will then not be at the same physical location as voxel (x,y,z) in the other cropped images, because the voxelgrids were defined differently. So in that case you would also need to resample to a common target space before applying CropAndPad right?

**Comment by romainVala** [comment]
The way I would like to use this, is for the case of resampling to a template, 
In this use case, there is no interest to add in each template to the data sample. 
So is it possible to have to possibility to specify a template image as argument ? 
or alternatively, just an an affine (no need to load the data, when only the affine matter !)

the next step is to handel also the case, where you have a "coregistration file" (affine transformation from fsl nifti_reg, ). an other possible argument ?

**Comment by romainVala** [comment]
> There is still one thing that I'm wondering about. CropAndPad won't accept images of different sizes and will only work when the voxelgrids are already align right?

I did not check, but it should work, why not ?

**Comment by romainVala** [comment]
> Because, if you have images with different voxelgrids. If you would resample them to isotropic voxels without also resampling to a common target space and then use CropAndPad. The resampled images will indeed have the same voxelsize and have the same shape after CropAndPad. However a voxel at location (x,y,z) in one image will then not be at the same physical location as voxel (x,y,z) in the other cropped images, because the voxelgrids were defined differently. So in that case you would also need to resample to a common target space before applying CropAndPad right?

it make it possible, but not sure, it will keep the coregistration correctly. ... it depends on the exact preprocessing and data origin
if the matter is to conserve the right coregistration then saffer way is indeed to resample
And if the matter is to have all subject align in the same space, then the extra option I just propose are need

**Comment by nwschurink** [comment]
> So is it possible to have to possibility to specify a template image as argument ?
> or alternatively, just an an affine (no need to load the data, when only the affine matter !)
> 
> the next step is to handel also the case, where you have a "coregistration file" (affine transformation from fsl nifti_reg, ). an other possible argument ?

I agree, this would be a nice additional feature indeed. I can imaging that for your usecase, you would now have to load in this template for every image, having such an argument would probably speed up the transforms.

**Comment by romainVala** [comment]
@fepegar 
you did not comment about the propose extension : 
1_ take a template a argument (either file path, to be load by nibabel, or directly an affine)
2_ take a "coregistration file" as argument, format as an affine, wich need to be multiplied the nifti affine, before to do the resampling

Doing so will allows to have all subjects in the same space,
If you are interested, I can try to make a new PR

**Comment by fepegar** [comment]
I think that maybe a universal `Resample` class is needed that merges `Resample`, `RandomAffine`, `RandomElasticDeformation` and adds the functionality you're proposing, but this should be discussed in a new issue.

**Comment by romainVala** [comment]
not sure : this is quite the opposite use :  here we are in preprocessing, and the randomAffine is used for augmentation

may be the coregistration file is a little out of scope, but very convenient though ...

**Comment by fepegar** [comment]
@all-contributors please add @romainVala for ideas, review

**Comment by fepegar** [comment]
@all-contributors please add @nwschurink for code

**Pull request merged**
