### PR TITLE
Catch fourier AttributeError when pytorch version < 1.8.0

### PR DESCRIPTION
**Pull request by chagelo**
Fixes [#967](https://github.com/fepegar/torchio/issues/967).

**Description**
Catch AttributeError in fourier.py, fftshift is not implemented in torch.fft when pytorch version < 1.8.0

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [ ] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [ ] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed
- [x] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

### CODE REVIEW

**Review by fepegar — CHANGES_REQUESTED** [review]
Hi, @chagelo. Thanks for reporting and for submitting the PR.

Note that

```python
In [1]: ModuleNotFoundError or AttributeError
Out[1]: ModuleNotFoundError

In [2]: AttributeError or ModuleNotFoundError
Out[2]: AttributeError
```

The correct syntax is `except ModuleNotFoundError, AttributeError):`

Could you please change that?

**Comment by chagelo** [comment]
Sorry......, I get you and I have make a change.

**Review by fepegar — APPROVED** [review]
Thanks for your contribution, @chagelo.

**Comment by fepegar** [comment]
@all-contributors please add @chagelo for bug

**Pull request merged**
