### PR TITLE
Add option to keep copies of original images

### LINKED ISSUE #93: Add option to keep original image in sample after applying a transform
As discussed in #26.

### PR DESCRIPTION
**Pull request by fepegar**
Resolves #93.

**Description**
This adds a kwarg to keep images in subject untouched after applying the transform.

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/master/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [x] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [x] In-line docstrings updated
- [x] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed
- [ ] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

### CODE REVIEW

**Comment by dmus** [comment]
Just a question, does something like this work:

```
transform =tio.Compose([
    tio.Resample(...), 
    tio.Pad(...),
    tio.RescaleIntensity((0, 1))
])
subject_transformed = transform(subject_original)
prediction_data = predict(subject_transformed['mri'][tio.DATA])
prediction = Image(data=prediction_data, affine=subject_transformed.get_first_image()[tio.AFFINE]
inverse_transform = subject_transformed.get_inverse_transform()
subject_original['prediction'] = inverse_transform(prediction)
```

I mean, is subject_original untouched?

**Comment by romainVala** [comment]
Great I haded a similar change in my fork, Just curious what application do you have in mind with this ?

**Comment by fepegar** [comment]
@dmus 

> I mean, is subject_original untouched?

It should be, but there are certain subtleties that need to be taken care of. There's a balance between consistency and efficiency, and I haven't had time to think about this deeply. See #345, for example.

In your example, instead of `Image` I would use `LabelMap` if you want to undo the transform using NN interpolation, and `ScalarImage` if you don't. Also, I would use `subject_original.add_image(inverse_transform(prediction), 'prediction')` for the last line, so you can access it as `subject.prediction`.

---

@romainVala 

> Great I haded a similar change in my fork, Just curious what application do you have in mind with this?

None, I just remembered that you were interested in this and thought that it was now easy to implement. I suppose this is useful for e.g. regression and registration, on which I'm not working. Unfortunately, I'm very biased to brain MRI segmentation!

**Comment by dmus** [comment]
So I guess then I should make it like this to make sure the original data is untouched?:

```
transform =tio.Compose([
    tio.Resample(...), 
    tio.Pad(...),
    tio.RescaleIntensity((0, 1))
])
subject_original_copy = deepcopy(subject_original)
subject_transformed = transform(subject_original_copy)
prediction_data = predict(subject_transformed['mri'][tio.DATA])
prediction = ScalarImage(data=prediction_data, affine=subject_transformed.get_first_image()[tio.AFFINE]
inverse_transform = subject_transformed.get_inverse_transform()
subject_origina.add_image(inverse_transform(prediction))
```

But seeing the unit test this is not what this PR is about?

**Comment by fepegar** [comment]
I don't think you need the `deepcopy`. The transform makes a shallow copy, so you should be fine.

But you're correct, this PR is unrelated!

**Pull request merged**
