### PR TITLE
Revert invertibility of `RescaleIntensity`

### PR DESCRIPTION
**Pull request by fepegar**
Implement changes proposed in #1116.

@nicoloesch @romainVala @mueller-franzes

### CODE REVIEW

**Review by nicoloesch — CHANGES_REQUESTED** [review]
The transform is in the current state (with the proposed changes) still invertible as it has the attribute `self.revert_transform` (see `transform.py` in L.403 with the method `is_invertible`). As such, I would suggest to either overwrite `is_invertible` as proposed in #1116 or removing the entire code part for `invert_transform`. I would suggest the former as we do not loose any functionality nor do we make it more complicated - we just need to update the docstring (which has already been done in #1116 in my stashes but I am awaiting the response of all people of the issue). If that is choosen, the test needs to be adapted and needs to have two checks - one that it fails if `in_min_max` is not provided and one where it actually is invertible and that the inverse is the same again.

**Comment by fepegar** [comment]
You're right, this still needs some work. I'll let you choose on top of these changes or your stash.

I didn't get this bit though:

> the test needs to be adapted and needs to have two checks - one that it fails if in_min_max is not provided and one where it actually is invertible and that the inverse is the same again.

Shouldn't we get rid of those tests?

**Comment by romainVala** [comment]
thanks @nicoloesch ! sound good to me

**Comment by fepegar** [comment]
Given the importance of the bug, I'm going to go ahead and merge this PRs. The code is still in the repo's history if we ever needed back. Thank you all for your contribution!

**Comment by fepegar** [comment]
https://github.com/all-contributors please add @nicoloesch @romainVala @mueller-franzes for bug

**Pull request merged**
