### PR TITLE
Add support to slice images and subjects

### LINKED ISSUE #1011: Add pythonic slicing support to torchio.Image
**🚀 Feature**

Allow torchio.Image to be sliced like numpy arrays
```python
image = torchio.Image(...)
print(image.spatial_shape) # -> (100, 100, 100)

crop = image[10:20, :, ::2] # returns a new ScalarImage where the affine matrix and data have been modified accordingly
print(crop.spatial_shape) # -> (10, 100, 50)

# image['data'] or image['affine'] would still work
```

If the image is not yet loaded when the slicing is applied, it would modify the affine and when the image is finally loaded, it would load only the given slice, making use of NiBabel's slicing [https://nipy.org/nibabel/nibabel_images.html#image-slicing](https://nipy.org/nibabel/nibabel_images.html#image-slicing).

**Motivation**

- More pythonic cropping.
- Easier subsampling and flipping.
- Much faster patch loading for patch-based pipelines.

**Additional context**

The `__getitem__` method of `torchio.Image` could look like this:
```python
def __getitem__(self, item):
    if isinstance(item, str):
        if item in (DATA, AFFINE):
            if item not in self:
                self.load()
        return super().__getitem__(item)
    else:
        check_validity(item) # do some checks
        if not isinstance(item, tuple):
            item = (item,)
        self.affine = modify_affine(self.affine, item) # to be implemented.
        if not self._loaded:
            self._slice = modify_slice(self._slice, item) # to be implemented. self._slice will be used when the
                                                          # image is finally loaded into memory. It would be
                                                          # initialized as an empty tuple.
        else:
            self.set_data(self.data[(slice(None), *item)]) # add the channel dim
        return self
```
Whether to modify the image inplace or to return a new image must be discussed.

### PR DESCRIPTION
**Pull request by fepegar**
Resolves #1011.

**Description**

See @marius-sm's [feature request](https://github.com/fepegar/torchio/issues/1011#issue-1509410933).

I would appreciate it if someone could please take a look!
@marius-sm @abenicho @wahabk @HyunKyungHan

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [x] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [ ] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed

### CODE REVIEW

**Review by abenicho — APPROVED** [review]

**Comment by fepegar** [comment]
@allcontributors please add @marius-sm for ideas

**Comment by marius-sm** [comment]
Hi @fepegar, very nice! Sorry for not contributing more myself. I am not coding anymore at the moment.

**Comment by fepegar** [comment]
No worries!

**Comment by fepegar** [comment]
I hope you're ok with being added to the contributor list.

**Comment by marius-sm** [comment]
Sure, thanks!

**Pull request merged**
