### PR TITLE
Add SubjectsLoader

### LINKED ISSUE #1179: Supporting PyTorch 2.3
PyTorch 2.3 would be forcibly replaced with PyTorch 2.2 when installing the latest TorchIO (0.19.7), breaking Torchvision installed.

### PR DESCRIPTION
**Pull request by fepegar**
Fixes #1179.

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [x] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [x] In-line docstrings updated
- [x] Documentation updated, tested running `make html` inside the `docs/` folder
- [ ] This pull request is ready to be reviewed

### CODE REVIEW

**Comment by fepegar** [comment]
@romainVala

**Comment by rickymwalsh** [comment]
Looks good to me :) I tested it on the issues with Lightning and it fixed both the MWE from https://github.com/fepegar/torchio/issues/1179#issuecomment-2204658903 and the code from https://github.com/fepegar/torchio/issues/1189.

**Comment by romainVala** [comment]
thanks for the PR, it looks indeed good (As always rigorous with the typing !)
nice

**Comment by fepegar** [comment]
Thank you both for checking!

> thanks for the PR, it looks indeed good (As always rigorous with the typing !)

I wish! I tried very hard to annotate `_stack` properly and ended up giving up.

@rickymwalsh, I'm adding you to the merge commit as you implemented the loader. I'll also ask the bot to add you as a contributor to the project. I hope that's ok!

**Comment by fepegar** [comment]
@allcontributors please add @rickymwalsh for bug and code

**Comment by fepegar** [comment]
@allcontributors please add @rickymwalsh for code

**Comment by fepegar** [comment]
Ok I'm having a little fight with the bot.

**Comment by rickymwalsh** [comment]
Thanks @fepegar, I just built on the nice work by @c-winder. Happy to help in some way, as I've found Torchio really useful!

**Pull request merged**
