### PR TITLE
Add support to average overlapping patches in aggregator

### PR DESCRIPTION
**Pull request by soumickmj**

### CODE REVIEW

**Comment by fepegar** [comment]
I added some tests, checks and docs. Please, let me know what you think.

**Comment by fepegar** [comment]
@soumickmj would you like to take a look?

**Comment by soumickmj** [comment]
@fepegar Sorry, I was bit occupied with some deadline. I will have a look and let you know real soon.

**Comment by soumickmj** [comment]
@fepegar Looks good to me. Can you please merge then?
Also, I will push the H5 lazy loading for Image and then create Pull request for the same.

**Comment by fepegar** [comment]
Thanks. Can you please remove that last commit? It's unrelated to this PR. I think you can do `git reset HEAD~ && git push --force`.

It'd be great if you could open a new PR with that code. I'll merge after that.

**Comment by soumickmj** [comment]
@fepegar ya sure. My bad, sorry

**Comment by fepegar** [comment]
@all-contributors please add @soumickmj for code

**Comment by fepegar** [comment]
Added in `v0.17.45`. Thanks for your contribution, @soumickmj!

**Comment by soumickmj** [comment]
Most welcome @fepegar 😄 
Hoping to be able to contribute more in future

**Comment by fepegar** [comment]
(Related to #304)

**Pull request merged**
