### PR TITLE
Fix HistogramStandardization example

### PR DESCRIPTION
**Pull request by vedal**
Fixes #{issue_number}.

**Description**
Currently the example isn't loading the landmarks from path. This PR fixes that.

**Checklist**

- [v] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [v] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [ ] Tests added or modified to cover the changes
- [ ] Integration tests passed locally by running `pytest`
- [v] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [v] This pull request is ready to be reviewed
- [ ] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

### CODE REVIEW

**Comment by fepegar** [comment]
Hi, @vedal. Please read the contributing guide as requested in the PR template.

According to the documentation, this transform supports paths to NumPy arrays, so this change is not needed.

**Comment by vedal** [comment]
Hi @fepegar, thanks for reviewing this. I think particularly the change to add a torch.load makes the example more readable, since the variable name "t1_landmarks" suggests its not a path (such as "t1_landmarks_path" used previously). 
As such, the change might not be necessary but at least increase readiblity.

Also, its unusual to store .npy with torch.save, as done if running the example once.

**Comment by fepegar** [comment]
Thanks for clarifying, that makes sense. I'll take a look later.

**Comment by fepegar** [comment]
I think the idea is that the list of landmarks is saved an an `npy` file, and `pth` would be used for a pickled dict. So I think the change I would do is replace `torch.save(t1_landmarks, t1_landmarks_path)` with `np.save(t1_landmarks_path, t1_landmarks)`. What do you think?

**Comment by fepegar** [comment]
@all-contributors please add @vedal for doc

**Pull request merged**
