### PR TITLE
Fix copying of subclasses of Subject

### LINKED ISSUE #694: Use of self.__class__ in __copy__ method of Subject
**🚀 Feature**
possibility to inherit torchio Subject

**Motivation**

In our current workflow we want to build on top of the torchio framework. We have subjects with 2 mandatory properties, a study name and a patient id. Therefore we have a subject class that looks like this:

```python
class Subject(tio.Subject):

    def __init__(self, study_name: str, patient_id: str, *args, **kwargs):
        kwargs['study_name'] = study_name
        kwargs['patient_id'] = patient_id
        super().__init__(*args, **kwargs)
```
**Pitch**

What I would like to see is that this method:

```python
    def __copy__(self):
        result_dict = {}
        for key, value in self.items():
            if isinstance(value, Image):
                value = copy.copy(value)
            else:
                value = copy.deepcopy(value)
            result_dict[key] = value
        new = Subject(result_dict)
        new.applied_transforms = self.applied_transforms[:]
        return new
```
is replaced by

```python
    def __copy__(self):
        result_dict = {}
        for key, value in self.items():
            if isinstance(value, Image):
                value = copy.copy(value)
            else:
                value = copy.deepcopy(value)
            result_dict[key] = value
        new = self.__class__(**result_dict)
        new.applied_transforms = self.applied_transforms[:]
        return new
```
to make custom subject classes that inherit torchio Subject compatible with the other components in the framework. The Image class has already a  __copy__ method that uses __class__ property.

**Alternatives**

The alternative is overwriting the __copy__ method in the custom classes that inherit torchio subject. However, this seems less future proof.

### PR DESCRIPTION
**Pull request by justusschock**
Fixes #694 .

**Description**
Adds support (and tests) for copying subclasses.

Tests seem to be cleaner than #718 . Approach is almost the same!

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [x] Tests added or modified to cover the changes
- [ ] Integration tests passed locally by running `pytest`
- [ ] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed
- [x] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

### CODE REVIEW

**Comment by justusschock** [comment]
@fepegar can you re-run the tests ? It seems they failed to to connection errors...

**Comment by fepegar** [comment]
> @fepegar can you re-run the tests ? It seems they failed due to connection errors...

Done, I've re-started the jobs.

---

@dmus, can you please review this PR?

**Comment by fepegar** [comment]
@justusschock looking at [the build logs on RTD](https://readthedocs.org/projects/torchio/builds/15827887/), I think this implementation isn't working.

**Comment by justusschock** [comment]
@fepegar I see that.

However,  After investigating a bit, I think this is because the pre-defined subjects (e.g. in `dataset`) break with the usual subject API by not accepting the images and other metadata as init arguments but only a year. This violates the liskov substitution principle. Usually the stuff happening there (like building the subject from a given version) would be a classmethod or a helper method but not part of the `__init__`.

**Comment by fepegar** [comment]
Ok, thanks. I hadn't heard of the Liskov substitution principle. I'm not sure why the tests failed on ReadTheDocs but not in the GitHub action. Let's see if @dmus is happy with the changes and then we can merge.

**Comment by fepegar** [comment]
> I'm not sure why the tests failed on ReadTheDocs but not in the GitHub action

This happens because RTD uses `Colin27` etc to create the gallery, but those are not called in the unit tests, which is problematic here. Maybe we should add a unit test that instantiates e.g. `Colin27`, to make sure this PR is compatible with those subclasses.

**Comment by justusschock** [comment]
@fepegar to resolve this with colin27 etc. we could do one of two things: Resolve this by moving the dict building to a class method or introduce a special copy function there :) What would you prefer?

**Comment by fepegar** [comment]
I'm not sure what each option would imply, but I'd rather not have to modify all the current subclasses with new methods.

**Comment by justusschock** [comment]
@fepegar The first method would be the cleaner way in terms of API, but would however require changes from the user-side. 
There we would move all the code from the init-function to a classmethod like `from_year` which users would have to call then.

The second approach would be to copy-paste the current `__copy__` function to all the required subclasses (or at least a subset of them since for all the MNI things, only one copy would be necessary). This would then not require any additional user-interaction.

After looking at the code again, a third approach came to my mind:

Instead of having derived classes like `Colin27`, we could have a function with the same name that would just prepare the images dict and return it as an ordinary subject.

**Comment by dmus** [comment]
changes look good. Other maybe related (or maybe another pr) question: when passing an Image or numpy array to a transform a temporary torchio Subject is created. Should it be possible to also have the custom Subject class there?

**Comment by justusschock** [comment]
@dmus yes, I think this should just use the copy mechanism and that would be changed here. Will update after resolving the issues with the builtin datasets.

**Comment by fepegar** [comment]
**Option 1: "moving the dict building to a class method"**
Would this break the current API? E.g. `colin = tio.datasets.Colin27()`.

**Option 2: "introduce a special copy function there"**
I feel like we shouldn't paste a lot of copies of a `__copy__` method in all the current subclasses.

**Option 3: "have a function with the same name that would just prepare the images dict and return it as an ordinary subject"**

Does this PR solve the original issue? Also, I think some current subclasses have some methods that would be lost. Maybe I have misunderstood this approach.

**Comment by justusschock** [comment]
> Option 1: "moving the dict building to a class method"
Would this break the current API? E.g. colin = tio.datasets.Colin27().

Unfortunately yes. So while this would be the cleanest option from the programming side, I think breaking this API is off the table.

> Option 2: "introduce a special copy function there"
I feel like we shouldn't paste a lot of copies of a __copy__ method in all the current subclasses.

Well we could separate this into a helper function we just call if this is your main concern.


> Option 3: "have a function with the same name that would just prepare the images dict and return it as an ordinary subject"
Does this PR solve the original issue? Also, I think some current subclasses have some methods that would be lost. Maybe I have misunderstood this approach.

Yes it does, since this issue arises from the `__init__` of these subjects being different, which it wouldn't be any more.
We could also have subclasses that have everything and just a function calling those.

**Comment by dmus** [comment]
How is progress going here?

**Comment by dmus** [comment]
@justusschock @fepegar any updates here?

**Comment by justusschock** [comment]
@dmus not from my side. Waiting on @fepegar to decide. So far I implemented the "proper" copying in a custom subclass which I don't really like, but is the current way to go

**Comment by fepegar** [comment]
Apologies, guys. TorchIO has moved a bit in my list of priorities.
What is your preferred option?

**Comment by justusschock** [comment]
Personally, I'd probably go with Option 2. Thoughts @dmus ?

**Comment by dmus** [comment]
I do not have a strong preference, the most important is that the original issue will be solved.
I agree option 1 is the cleanest option, followed by option 3. Option 2 seems less clean, but keeps the API untouched if I understand it correctly. So if that is a hard requirement, that is the way to go

**Comment by fepegar** [comment]
Option 2 it is, then.

> Well we could separate this into a helper function we just call if this is your main concern.

@justusschock, can you add that to this PR?

**Review by fepegar — APPROVED** [review]

**Comment by fepegar** [comment]
I've built the docs, which make extensive use of these subclasses. Lacking better tests, I think this is good to go! Thanks a lot for your contributions, @justusschock and @dmus!

**Pull request merged**
