### PR TITLE
Fix fourier

### PR DESCRIPTION
**Pull request by chagelo**
Fixes [#967](https://github.com/fepegar/torchio/issues/967).

**Description**
Fix fourier implementation using numpy.fft rather than numpy.fft and torch.fft.

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [ ] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [ ] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed
- [x] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

### CODE REVIEW

**Comment by chagelo** [comment]
> Fixes #{967}.
> 
> **Description** Fix fourier implementation use numpy.fft rather than numpy fft and torch.fft.
> 
> **Checklist**
> 
> * [x]  I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
> * [x]  Non-breaking change (would not break existing functionality)
> * [ ]  Breaking change (would cause existing functionality to change)
> * [ ]  Tests added or modified to cover the changes
> * [x]  Integration tests passed locally by running `pytest`
> * [ ]  In-line docstrings updated
> * [ ]  Documentation updated, tested running `make html` inside the `docs/` folder
> * [x]  This pull request is ready to be reviewed
> * [x]  If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

**Review by romainVala — COMMENTED** [review]
I do not understand why do you want to remove the torch.fft ?
with the current implementation if torch.fft does not work it then go with the numpy fft
what is the problem ?

**Comment by chagelo** [comment]
@romainVala Please refer to [#967](https://github.com/fepegar/torchio/issues/967), torch.fft.fftshift not implemented when pytorch version < 1.8.0

**Comment by romainVala** [comment]
> @romainVala Please refer to [#967](https://github.com/fepegar/torchio/issues/967), torch.fft.fftshift is not implemented when pytorch version < 1.8.0

I still do not understand, with the current implementation (try except) if fftshift is not implemented it should use the numpy fft ...
may be you just need to change 
except ModuleNotFoundError:
in order to also catch AttributeError

**Comment by chagelo** [comment]
You are right(I just need to change ModuleNotFoundError to AttributeError), but i don't know that what time there is a ModuleNotFoundError in previous implementation. And I think using numpy only is more clean, this is my the first pr, so don't mind..., then what should i do? cancel this pr?

Another question is, i see [here](https://github.com/fepegar/torchio/pull/207#issuecomment-650069939), you mentioned a other motion generation. When I use torchio's randommotion, i get unwanted result, not like this [real motion](https://github.com/chagelo/basic-subjects/blob/master/s45scan_1.png), so i want to know about better simulation result.

**Comment by romainVala** [comment]
just keep both 
except ModuleNotFoundError or AttributeError :

About motion correction, we can discuss elswere, but you may give a try to my implementation, there
https://github.com/romainVala/torchio/blob/master/src/torchio/transforms/augmentation/intensity/random_motion_from_time_course.py

**Comment by chagelo** [comment]
Sorry, you mean i go to change ModuleNotFoundError  to AttributeError ?(otherwise, it will still return a AttributeError, in my pytorch version 1.8.0)

And thanks for this

>https://github.com/romainVala/torchio/blob/master/src/torchio/transforms/augmentation/intensity/random_motion_from_time_course.py

I'll go to read it. And could you leave a contact？(this is my email changeto104@gmail.com)

**Comment by romainVala** [comment]
> Sorry, you mean i go to change ModuleNotFoundError to AttributeError ?(otherwise, it will still return a AttributeError, in my pytorch version 1.8.0)

just catch both exeption with a OR condition

**Comment by chagelo** [comment]
Thank you! I am goona do it.

**Pull request closed without merging**
